# Site settings
author: Alexander Cleasby
title: AlwaysLearning
header-img: img/home-bg.png
email: cleasby.alex@gmail.com
copyright_name: Alexander Cleasby
description: > # this means to ignore newlines until "baseurl:"
  Learn something with me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AlexanderCleasby

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
